# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3aaa5f1686b465476cbb10af28ef08f3cd7368349d82eb101824ed84dd6698396e0be5f8debca35ce84ac3b49216a157cd5b074e54194a7d98da736584728ce

test:
  secret_key_base: 359d662b41a503cc6505a53fb2f610d9e7f2941409f1ae89e95d15c408f450b7c4552dce1e8fec65c761749d1b690e68531171f926cc752a09da2d6a02521c55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
